# Generated by Django 5.0.1 on 2026-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Garage', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('currency_code', models.CharField(default='UGX', max_length=10)),
                ('currency_symbol', models.CharField(default='UGX', max_length=10)),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for your business!')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Garage Settings',
                'verbose_name_plural': 'Garage Settings',
            },
        ),
    ]
