# Generated by Django 5.0.1 on 2026-10-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('stock_adjust', 'Stock Adjustment'), ('reconcile', 'Reconciliation'), ('payment', 'Payment'), ('expense', 'Expense')], max_length=30),
        ),
    ]
