# Generated by Django 5.0.1 on 2026-10-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='debtpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='debt',
            name='promised_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
